name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - MAJOR
        - MINOR
    validations:
      required: true
  - type: textarea
    id: actual-behaviour
    attributes:
      label: Actual behaviour
      description: What happened, that should not have happened?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
      description: What should have happened?
      placeholder: When x the program should y
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: What steps do you take to reproduce the bug?
      placeholder: Go to the website, click on the button, and then click on the button again...
      value: |
        1. 
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: attatchments
    attributes:
      label: Attatchments
      description: Please attatch images and videos/GIFs or a link to paint a better picture of the bug.
